/*################################################################
#   Snowflake Tasks for Triggering gold table load from streams  #
################################################################*/

--Task for loading customer data
CREATE OR REPLACE TASK DBS_ANALYTICS.PUBLIC.LOAD_CUSTOMER_DIM_TASK
  WAREHOUSE = ANALYTICS_LARGE
  SCHEDULE = '1 minute'
WHEN
  SYSTEM$STREAM_HAS_DATA('DBS_ANALYTICS.CUSTOMER.RAW_CUSTOMER_DIM_STREAM')
AS
  INSERT INTO DBS_ANALYTICS.CUSTOMER.CUSTOMER_DIM 
  SELECT USER_ID, USER_EMAIL,USER_NAME,SOURCE,IS_PRIME,SIGNUP_TIME, 
  CURRENT_TIMESTAMP AS CREATE_DATETIME,CURRENT_TIMESTAMP AS UPDATE_DATETIME 
  FROM DBS_ANALYTICS.CUSTOMER.RAW_CUSTOMER_DIM_STREAM;

--Alter command to resume the task
ALTER TASK DBS_ANALYTICS.PUBLIC.LOAD_CUSTOMER_DIM_TASK RESUME;

--ALter command to suspend the task when not requried
ALTER TASK DBS_ANALYTICS.PUBLIC.LOAD_CUSTOMER_DIM_TASK SUSPEND;

--Task for loading sales transaction data
CREATE OR REPLACE TASK DBS_ANALYTICS.PUBLIC.LOAD_SALES_TRANSACTION_FACT_TASK
  WAREHOUSE = ANALYTICS_LARGE
  SCHEDULE = '1 minute'
WHEN
  SYSTEM$STREAM_HAS_DATA('DBS_ANALYTICS.SALES.RAW_SALES_TRANSACTION_FACT_STREAM')
AS
  INSERT INTO DBS_ANALYTICS.SALES.SALES_TRANSACTION_FACT 
  SELECT TRANSACTION_ID,USER_ID,PRODUCT_ID,TRANSACTION_TIME,TRANSACTION_TYPE,
  PRICE,SALES_QUANTITY,GEOG_ID,CURRENT_TIMESTAMP AS CREATE_DATETIME,CURRENT_TIMESTAMP AS UPDATE_DATETIME 
  FROM DBS_ANALYTICS.SALES.RAW_SALES_TRANSACTION_FACT_STREAM;

--Alter command to resume the task
ALTER TASK DBS_ANALYTICS.PUBLIC.LOAD_SALES_TRANSACTION_FACT_TASK RESUME;

--ALter command to suspend the task when not requried
ALTER TASK DBS_ANALYTICS.PUBLIC.LOAD_SALES_TRANSACTION_FACT_TASK SUSPEND;
